In [1]:
import tensorflow as tf

In [8]:
data = [4,5,7,2,3,6]
dataset = tf.data.Dataset.from_tensor_slices(data)

dataset = dataset.batch(3)
iterator = dataset.__iter__()
print(iterator.get_next())
print(iterator.get_next())


tf.Tensor([4 5 7], shape=(3,), dtype=int32)
tf.Tensor([2 3 6], shape=(3,), dtype=int32)


In [10]:
dataset = dataset.map (lambda x: x ** 2)
dataset = dataset.batch(2)

dataset = dataset.map(lambda x: x ** 2)
dataset = dataset.batch(2)


In [13]:
for batch in dataset:
   print(batch. numpy())

for batch in dataset:
  print(batch.numpy())


[[[ 256  625 2401]
  [  16   81 1296]]]
[[[ 256  625 2401]
  [  16   81 1296]]]


In [14]:
# Define a simple Sequential model
model = tf.keras.Sequential([
  tf.keras.layers.Dense(32, activation='relu', input_shape=(64,)), # First layer
  tf.keras.layers.Dense(64, activation='relu'), # Second layer
  tf.keras.layers.Dense(10, activation='softmax') # Output layer
])
# Print model summary
model.summary()


/usr/local/lib/python3.10/dist-packages/keras/src/layers/core/dense.py:87: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)


Model: "sequential"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━┓
┃ Layer (type)                         ┃ Output Shape                ┃         Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━┩
│ dense (Dense)                        │ (None, 32)                  │           2,080 │
├──────────────────────────────────────┼─────────────────────────────┼─────────────────┤
│ dense_1 (Dense)                      │ (None, 64)                  │           2,112 │
├──────────────────────────────────────┼─────────────────────────────┼─────────────────┤
│ dense_2 (Dense)                      │ (None, 10)                  │             650 │
└──────────────────────────────────────┴─────────────────────────────┴─────────────────┘

 Total params: 4,842 (18.91 KB)

 Trainable params: 4,842 (18.91 KB)

 Non-trainable params: 0 (0.00 B)

In [16]:
# prompt: # Input layer
inputs = tf. keras. Input (shape=(64, ))
# # First hidden layer
x = tf. keras. layers. Dense(32, activation='relu' )(inputs)
# # Second hidden layer
x = tf. keras. layers. Dense(64, activation='relu' )(x)
# # Output layer
outputs = tf. keras. layers. Dense(10, activation='softmax') (x)
# # Define the model
model = tf. keras.Model (inputs=inputs, outputs=outputs)
# # Summary of the model
model.summary()


Model: "functional_1"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━┓
┃ Layer (type)                         ┃ Output Shape                ┃         Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━┩
│ input_layer_1 (InputLayer)           │ (None, 64)                  │               0 │
├──────────────────────────────────────┼─────────────────────────────┼─────────────────┤
│ dense_3 (Dense)                      │ (None, 32)                  │           2,080 │
├──────────────────────────────────────┼─────────────────────────────┼─────────────────┤
│ dense_4 (Dense)                      │ (None, 64)                  │           2,112 │
├──────────────────────────────────────┼─────────────────────────────┼─────────────────┤
│ dense_5 (Dense)                      │ (None, 10)                  │             650 │
└──────────────────────────────────────┴─────────────────────────────┴─────────────────┘

 Total params: 4,842 (18.91 KB)

 Trainable params: 4,842 (18.91 KB)

 Non-trainable params: 0 (0.00 B)

In [17]:
class MyModule(tf.Module):
  def __init__(self):
    self.weight = tf.Variable([10,20])
  def __call__(self,x):
    return self.weight * x


In [18]:
#MyModule = MyModule()

m = MyModule()


In [19]:
#  MyModule. call (5). numpy()

m(tf.constant([5])).numpy()


array([ 50, 100], dtype=int32)

In [20]:
class Module2(tf.Module):
  def __init__(self):
    self.age = tf.Variable(18)
  def __call__(self, x):
    return self.age + x

m2 = Module2()
m2(tf.constant([10])).numpy()


array([28], dtype=int32)

In [21]:
m2 = Module2()
m2(tf.constant([19])).numpy()


array([37], dtype=int32)