In [ ]:
import tensorflow as tf

In [ ]:
categories = tf.constant([0, 1, 2, 0, 1, 2])

In [ ]:
num_categories = 3
encoding_layer = tf.keras.layers.CategoryEncoding(
  num_tokens=num_categories, output_mode="one_hot"
)
encoded_data = encoding_layer(categories)


In [ ]:
categories2 = tf.constant([1,2,4,1,4,2,1,3,4,3])
encoding_layer2 = tf.keras.layers.CategoryEncoding(num_tokens=5, output_mode="one_hot") # categories start from 1, so num_tokens should be 5
encoded_data2 = encoding_layer2(categories2)
encoded_data2.numpy()


array([[0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 1.],
       [0., 1., 0., 0., 0.],
       [0., 0., 0., 0., 1.],
       [0., 0., 1., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.],
       [0., 0., 0., 1., 0.]], dtype=float32)

In [ ]:
categories = tf.constant (["apple", "banana", "cherry", "apple", "banana", "cherry"])
hashing_layer = tf.keras.layers.Hashing(num_bins=3)
hashed_data = hashing_layer(categories)
hashed_data.numpy()


array([1, 0, 1, 1, 0, 1])

In [ ]:
categories3 = tf.constant (['A', 'B', 'C', 'B', 'B', 'A', "C"])
hashing_layer2= tf.keras.layers.Hashing(num_bins= 4)
hashed_data2 = hashing_layer2(categories3)
hashed_data2.numpy()


array([0, 0, 3, 0, 0, 0, 3])

In [ ]:
# prompt: dookupstayer = tr. Keras. dayers. StrangLookup)
# 囗 o
# v [38] 100kup_layer. adapt (categories)
# [39] encoded_data = 100kup_layer (categories)
# / [40] encoded_data. numpy ()

lookup_layer = tf.keras.layers.StringLookup()
lookup_layer.adapt(categories)
encoded_data = lookup_layer(categories)
encoded_data.numpy()


In [ ]:
lookup_layer2 = tf.keras.layers.StringLookup()
lookup_layer2.adapt(categories3)
encoded_data3 = lookup_layer2(categories3)
encoded_data3.numpy()


array([3, 1, 2, 1, 1, 3, 2])

In [ ]:
categories4 = tf.constant ( [55,33,88,44,22,33, 55,88])
integer_lookup_layer2 = tf.keras.layers.IntegerLookup()
integer_lookup_layer2.adapt(categories4)
encoded_data4 = integer_lookup_layer2(categories4)
encoded_data4.numpy()


array([2, 3, 1, 4, 5, 3, 2, 1])

In [11]:
# Sample categorical data
categories = ['red', 'blue', 'green', 'blue', 'red']

# Category Encoding
category_encoding_layer = tf.keras.layers.CategoryEncoding(num_tokens=4)
encoded_categories = category_encoding_layer(tf.constant([0, 1, 2, 1, 0]))
print('Category Encoding:\n', encoded_categories.numpy())

Category Encoding:
 [1. 1. 1. 0.]


In [12]:
# Hashing
hashing_layer = tf.keras.layers.Hashing(num_bins=4)
hashed_categories = hashing_layer(tf.constant(categories))
print('Hashing:\n', hashed_categories.numpy())

Hashing:
 [2 1 0 1 2]


In [13]:
# String Lookup
string_lookup_layer = tf.keras.layers.StringLookup()
string_lookup_layer.adapt(categories)
lookup_indices = string_lookup_layer(tf.constant(categories))
print('String Lookup:\n', lookup_indices.numpy())


String Lookup:
 [1 2 3 2 1]


In [14]:
# Integer Lookup
integer_lookup_layer = tf.keras.layers.IntegerLookup()
integer_lookup_layer.adapt([0, 1, 2])
integer_indices = integer_lookup_layer(tf.constant([0, 1, 2]))
print('Integer Lookup:\n', integer_indices.numpy())

Integer Lookup:
 [3 2 1]
