In [ ]:
import tensorflow as tf

# Example: Simple Sequential Model
model = tf.keras.Sequential([
  tf.keras.layers.Dense(76, activation=None, input_shape=(1,)),
  tf.keras.layers.Dense(1)
])


/usr/local/lib/python3.10/dist-packages/keras/src/layers/core/dense.py:87: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)


In [ ]:
model.compile(optimizer=tf.keras.optimizers.Adamax(learning_rate=0.001), loss=tf.keras.losses.MeanAbsoluteError(), metrics=['mae'])


In [ ]:
checkpoint_callback = tf.keras.callbacks.ModelCheckpoint(
    filepath='model.keras',
    save_best_only=True,
    monitor='val_loss',
    mode='min',
    verbose=1
)


Key Parameters:
filepath: The path where the model or weights will be saved. This can include placeholders like {epoch) or {val_loss) to include the epoch number or metric value in the filename.
save_best_only: If True, the model will only be saved when the monitored metric improves. This helps ensure you only keep the best version of the model.
not.
monitor: The metric to monitor, such as 'val_loss' or 'val_accuracy'. This is the metric that determines whether the model should be saved or
mode: Determines whether to look for the maximum or minimum value of the monitored metric. Use 'min' for metrics like loss (where lower is better) and 'max' for metrics like accuracy (where higher is better).
verbose: If 1, it prints messages about model saving. If 0, it is silent.

In [ ]:
X = tf.range(1, 101, 4)
X


<tf.Tensor: shape=(25,), dtype=int32, numpy=
array([ 1,  5,  9, 13, 17, 21, 25, 29, 33, 37, 41, 45, 49, 53, 57, 61, 65,
       69, 73, 77, 81, 85, 89, 93, 97], dtype=int32)>

In [ ]:
y = 2 * X + 3
y


<tf.Tensor: shape=(25,), dtype=int32, numpy=
array([  5,  13,  21,  29,  37,  45,  53,  61,  69,  77,  85,  93, 101,
       109, 117, 125, 133, 141, 149, 157, 165, 173, 181, 189, 197],
      dtype=int32)>

In [ ]:
# prompt: x = tf. cast(tf. constant (x), dtype = tf.float32)
# = tf. cast(tf.constant(y), dtype = tf.float32)
# +

x = tf.cast(tf.constant(X), dtype=tf.float32)
y = tf.cast(tf.constant(y), dtype=tf.float32)

history = model.fit(x, y, epochs=100, validation_split=0.2, callbacks=[checkpoint_callback])


In [ ]:
# prompt: model. fit(x,y, epochs=500)

history = model.fit(x, y, epochs=500)


In [ ]:
# prompt: import numpy as np
# predict = model. predict(np. array ( [5.0]) ›

import numpy as np
predict = model.predict(np.array([5.0]))


In [ ]:
import numpy as np
predict = model.predict(np.array([10.0]))
predict


1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 86ms/step


array([[-3.059674]], dtype=float32)