In [1]:
import tensorflow as tf
import numpy as np

In [2]:
#tensor1 = tf. constant ([0, 1, 0, 1], dtype=tf. int32)
# tensor. numpy ( )

tensor1 = tf.constant([0, 1, 0, 1], dtype=tf.int32)
tensor1.numpy()


array([0, 1, 0, 1], dtype=int32)

In [3]:
#tensor2 = tf. constant ([1, 0, 1, 0], dtype=tf.int32)
# tensor2. numpy ( )

tensor2 = tf.constant([1, 0, 1, 0], dtype=tf.int32)
tensor2.numpy()


array([1, 0, 1, 0], dtype=int32)

In [4]:
# Bitwise AND
# bitwise_and = tf. bitwise.bitwise_and(tensorl, tensor2)
# print ("Bitwise AND: \n", bitwise_and. numpy ( ))

bitwise_and = tf.bitwise.bitwise_and(tensor1, tensor2)
print("Bitwise AND: \n", bitwise_and.numpy())


Bitwise AND: 
 [0 0 0 0]


In [5]:
# Bitwise OR
# bitwise_or = tf. bitwise.bitwise_or(tensor1, tensor2)
# print ("Bitwise OR: \n", bitwise_or.numpy ())

# Bitwise XOR
bitwise_xor = tf.bitwise.bitwise_xor(tensor1, tensor2)
print("Bitwise XOR: \n", bitwise_xor.numpy())

# Bitwise NOT
bitwise_not_t1 = tf.bitwise.invert(tensor1)
print("Bitwise NOT of tensor1: \n", bitwise_not_t1.numpy())


Bitwise XOR: 
 [1 1 1 1]
Bitwise NOT of tensor1: 
 [-1 -2 -1 -2]


In [7]:
# Bitwise XOR
# bitwise_xor = tf. bitwise.bitwise_xor(tensorl, tensor2)
# print ("Bitwise XOR: \n", bitwise_xor. numpy ( ))

# Bitwise OR
bitwise_or = tf.bitwise.bitwise_or(tensor1, tensor2)
print("Bitwise OR: \n", bitwise_or.numpy())


Bitwise OR: 
 [1 1 1 1]


In [11]:
#shape (3, 1)
tensor3 = tf. constant ([[1], [2], [3]], dtype=tf.float32)
# #shape (1, 4)
tensor4 = tf. constant ([[4, 5, 6, 7]], dtype=tf.float32)

# Perform broadcasting
result = tf.multiply(tensor3, tensor4)
print("Result of broadcasting:\n", result.numpy())


Result of broadcasting:
 [[ 4.  5.  6.  7.]
 [ 8. 10. 12. 14.]
 [12. 15. 18. 21.]]


In [13]:
# prompt: tf.add(tensor3, tensor4). numpy () #broadcasting!

tensor3 = tf.constant([[1, 2], [3, 4]], dtype=tf.int32)
tensor4 = tf.constant([5], dtype=tf.int32)
print(tf.add(tensor3, tensor4).numpy()) #broadcasting!

[[6 7]
 [8 9]]


In [14]:
# tensor = tf. constant ([[1, 2, 3]], dtype=tf.float32) # Shape (1, 3)
# tensor7. numpy ()

tensor7 = tf.constant([[1, 2, 3]], dtype=tf.float32) # Shape (1, 3)
tensor7.numpy()


array([[1., 2., 3.]], dtype=float32)

In [15]:
#tensor8 = tf. constant ([[4], [5], [6]], dtype=tf.float32) # Shape (3, 1)
# tensor8. numpy ( )

tensor8 = tf.constant([[4], [5], [6]], dtype=tf.float32) # Shape (3, 1)
tensor8.numpy()


array([[4.],
       [5.],
       [6.]], dtype=float32)

In [16]:
#  tf multiply(tensor7, tensor8). numpy ()

result = tf.multiply(tensor7, tensor8)
print(result.numpy())


[[ 4.  8. 12.]
 [ 5. 10. 15.]
 [ 6. 12. 18.]]


In [17]:
# t2 = tf. constant ([[10, 20, 30]], dtype=tf.float32) # Shape (1, 3)
# t2. numpy ()

t2 = tf.constant([[10, 20, 30]], dtype=tf.float32) # Shape (1, 3)
t2.numpy()


array([[10., 20., 30.]], dtype=float32)

In [18]:
# tf.divide(t1, t2). numpy ()

t1 = tf.constant([[40, 50, 60]], dtype=tf.float32)
print(tf.divide(t1, t2).numpy())


[[4.  2.5 2. ]]


In [19]:
# Create a generator with a specific seed
generator = tf.random.Generator.from_seed(42)
# Generate random numbers using the generator
r_numbers = generator.normal(shape=(4, 2))
print(r_numbers)


tf.Tensor(
[[-0.7565803  -0.06854702]
 [ 0.07595026 -1.2573844 ]
 [-0.23193763 -1.8107855 ]
 [ 0.09988727 -0.50998646]], shape=(4, 2), dtype=float32)


In [20]:
#_numbers2 = generator. normal (shape= (3,2))
# print(r_numbers2) #different numbers

r_numbers2 = generator.normal(shape=(3,2))
print(r_numbers2) #different numbers


tf.Tensor(
[[ 1.4680984  -0.69443417]
 [-0.56105393 -1.1563786 ]
 [ 0.6156109   0.67493457]], shape=(3, 2), dtype=float32)
