In [3]:
import tensorflow as tf
import os
import numpy as np

In [4]:
input_data = tf.random.normal((5, 3))
input_data

<tf.Tensor: shape=(5, 3), dtype=float32, numpy=
array([[-0.6712008 , -1.8851118 , -1.5508547 ],
       [ 0.04268172,  1.3200793 ,  0.36382324],
       [ 0.967861  , -0.8980523 ,  0.45149025],
       [-0.5980253 , -1.7579763 ,  1.5347741 ],
       [ 0.64138097,  0.6849222 , -2.0715907 ]], dtype=float32)>

In [7]:
# Adapt to the data
normalization_layer.adapt(input_data)

In [6]:
normalization_layer = tf.keras.layers.Normalization()
normalized_data = normalization_layer(input_data)
print(normalized_data)


tf.Tensor(
[[-0.6712008  -1.8851118  -1.5508547 ]
 [ 0.04268172  1.3200793   0.36382324]
 [ 0.967861   -0.8980523   0.45149025]
 [-0.5980253  -1.7579763   1.5347741 ]
 [ 0.64138097  0.6849222  -2.0715907 ]], shape=(5, 3), dtype=float32)


In [8]:
print(normalized_data)

tf.Tensor(
[[-0.6712008  -1.8851118  -1.5508547 ]
 [ 0.04268172  1.3200793   0.36382324]
 [ 0.967861   -0.8980523   0.45149025]
 [-0.5980253  -1.7579763   1.5347741 ]
 [ 0.64138097  0.6849222  -2.0715907 ]], shape=(5, 3), dtype=float32)


In [9]:
import numpy as np
data = np.array ([[1.], [2.], [3.], [4.], [5.]], dtype=np. float32)


In [12]:

# import numpy as np
# # Generate the 3D random normal tensor
random_tensor_3d = tf.random.normal (shape= (2,3,4))
# <>
# # Print the tensor
# print (random_tensor_3d)

# Insert this code into the <> section
# Calculate the mean
mean = tf.reduce_mean(random_tensor_3d)

# Calculate the standard deviation
standard_deviation = tf.math.reduce_std(random_tensor_3d)

# Print the mean and standard deviation
print("Mean:", mean.numpy())
print("Standard Deviation:", standard_deviation.numpy())


Mean: -0.17031784
Standard Deviation: 0.8900731


In [17]:
 # Sample age data
 ages = tf.constant ([15, 25, 40, 62, 12, 33])
# # Define the bin boundaries
bin_boundaries = [0, 18, 30, 50, 100]
# # Create the discretization layer
discretization_layer = tf.keras. layers. Discretization (bin_boundaries)
# # Apply the layer to the age data
 discretized_ages = discretization_layer (ages)
 print ("Original ages:", ages)
 print ("Discretized ages:", discretized_ages.numpy ())


Original ages: tf.Tensor([15 25 40 62 12 33], shape=(6,), dtype=int32)
Discretized ages: [1 2 3 4 1 3]


In [19]:
# prompt: import tensorflow as tf
# # Set minimum and maximum values for the random uniform distribution
minval = -10
maxval = 10
# # Create a tensor with random uniform values between minval and maxval
data_1 = tf.random. uniform(shape=(5,1), minval=minval, maxval=maxval)
print (data_1)
# # Create a discretization layer with custom bin boundaries in ascending order!
discretization_layer = tf.keras.layers.Discretization(bin_boundaries=[-8., -5., 0., 5., 8.])

# Create a discretization layer with custom bin boundaries in ascending order!
discretization_layer = tf.keras.layers.Discretization(bin_boundaries=[-8., -5., 0., 5., 8.])

# Apply discretization to the data
discretized_data_1 = discretization_layer(data_1)
print("Discretized data 1:\n", discretized_data_1.numpy())


tf.Tensor(
[[5.8935432 ]
 [1.7591686 ]
 [0.58402824]
 [3.1220293 ]
 [9.471428  ]], shape=(5, 1), dtype=float32)
Discretized data 1:
 [[4]
 [3]
 [3]
 [3]
 [5]]
