In [ ]:
pip install --upgrade pip

  Using cached pip-24.2-py3-none-any.whl.metadata (3.6 kB)
Using cached pip-24.2-py3-none-any.whl (1.8 MB)
  Attempting uninstall: pip
    Found existing installation: pip 24.1.2
    Uninstalling pip-24.1.2:
      Successfully uninstalled pip-24.1.2


In [ ]:
pip install tensorflow

In [ ]:
import tensorflow as tf
print(tf.__version__)

2.17.0


In [ ]:
scaler = tf.constant(5,6)
scaler

<tf.Tensor: shape=(), dtype=int8, numpy=5>

In [ ]:
scaler.ndim

0

In [ ]:
vector = tf.constant([[5,6],[5,6]])
vector

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[5, 6],
       [5, 6]], dtype=int32)>

In [ ]:
vector.ndim

2

In [ ]:
vector = tf.constant([[[5,6],[5,6],[5,6]]],dtype= tf.int16)
vector.ndim
vector

<tf.Tensor: shape=(1, 3, 2), dtype=int16, numpy=
array([[[5, 6],
        [5, 6],
        [5, 6]]], dtype=int16)>

In [ ]:
matrix = tf.constant([[[10,6],[10,6],[10,6]]],dtype=tf.int16)
matrix

<tf.Tensor: shape=(1, 3, 2), dtype=int16, numpy=
array([[[10,  6],
        [10,  6],
        [10,  6]]], dtype=int16)>

In [ ]:
matrix.ndim

3

In [ ]:
matrix = tf.constant([[[10.5,6.10],[10.5,6.10],[10.5,6.10]]],dtype=tf.float32)
matrix

<tf.Tensor: shape=(1, 3, 2), dtype=float32, numpy=
array([[[10.5,  6.1],
        [10.5,  6.1],
        [10.5,  6.1]]], dtype=float32)>

In [ ]:
matrix.ndim

3

In [ ]:
tensor = tf.constant([[[[1,2,3],[2,3,4]],[[6,4,3],[2,3,4]],[[3,2,3],[2,4,3]]]])
tensor

<tf.Tensor: shape=(1, 3, 2, 3), dtype=int32, numpy=
array([[[[1, 2, 3],
         [2, 3, 4]],

        [[6, 4, 3],
         [2, 3, 4]],

        [[3, 2, 3],
         [2, 4, 3]]]], dtype=int32)>

In [ ]:
tensor.ndim

4

In [ ]:
tensor = tf.Variable([[[10,6],[10,6],[10,6]]])
tensor

<tf.Variable 'Variable:0' shape=(1, 3, 2) dtype=int32, numpy=
array([[[10,  6],
        [10,  6],
        [10,  6]]], dtype=int32)>

In [ ]:
tensor = tf.Variable([[[[1,2,3],[2,3,4]],[[6,4,3],[2,3,4]],[[3,2,3],[2,4,3]]]])
tensor

<tf.Variable 'Variable:0' shape=(1, 3, 2, 3) dtype=int32, numpy=
array([[[[1, 2, 3],
         [2, 3, 4]],

        [[6, 4, 3],
         [2, 3, 4]],

        [[3, 2, 3],
         [2, 4, 3]]]], dtype=int32)>

In [ ]:
matrix = tf.Variable([[[10,6],[10,6],[10,6]]],dtype= tf.int16)
matrix

<tf.Variable 'Variable:0' shape=(1, 3, 2) dtype=int16, numpy=
array([[[10,  6],
        [10,  6],
        [10,  6]]], dtype=int16)>

In [ ]:
matrix.assign([[[10,6],[10,6],[10,6]]])

<tf.Variable 'UnreadVariable' shape=(1, 3, 2) dtype=int16, numpy=
array([[[10,  6],
        [10,  6],
        [10,  6]]], dtype=int16)>

In [ ]:
matrix = tf.constant([[[10,6],[10,6],[10,6]]],dtype= tf.int16)
matrix

<tf.Tensor: shape=(1, 3, 2), dtype=int16, numpy=
array([[[10,  6],
        [10,  6],
        [10,  6]]], dtype=int16)>

In [ ]:
changeable_tensor= tf.Variable([10,4])
unchangeable_tensor= tf.constant([10,4])
changeable_tensor ,unchangeable_tensor
changeable_tensor == unchangeable_tensor

<tf.Tensor: shape=(2,), dtype=bool, numpy=array([ True,  True])>

In [ ]:
changeable_tensor[1].assign(2)
changeable_tensor


<tf.Variable 'Variable:0' shape=(2,) dtype=int32, numpy=array([10,  2], dtype=int32)>

In [ ]:
#Random number in TF

In [ ]:
random_1 = tf.random.Generator.from_seed(42)
random_1 = random_1.normal(shape=(2,3))
random_1

<tf.Tensor: shape=(2, 3), dtype=float32, numpy=
array([[-0.7565803 , -0.06854702,  0.07595026],
       [-1.2573844 , -0.23193763, -1.8107855 ]], dtype=float32)>

In [ ]:
random_1

<tf.Tensor: shape=(2, 3), dtype=float32, numpy=
array([[-0.7565803 , -0.06854702,  0.07595026],
       [-1.2573844 , -0.23193763, -1.8107855 ]], dtype=float32)>

In [ ]:
random_2 = tf.random.Generator.from_seed(42)
random_2 = random_2.normal(shape=(2,3))
random_2

<tf.Tensor: shape=(2, 3), dtype=float32, numpy=
array([[-0.7565803 , -0.06854702,  0.07595026],
       [-1.2573844 , -0.23193763, -1.8107855 ]], dtype=float32)>

In [ ]:
random_1,random_2
random_1==random_2

<tf.Tensor: shape=(2, 3), dtype=bool, numpy=
array([[ True,  True,  True],
       [ True,  True,  True]])>

In [ ]:
not_shuffled = tf.constant([[10,7],[3,4],[2,5]])
tf.random.shuffle(not_shuffled)

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[ 3,  4],
       [10,  7],
       [ 2,  5]], dtype=int32)>

In [ ]:
shuffled = tf.random.shuffle(not_shuffled)
shuffled

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[ 2,  5],
       [ 3,  4],
       [10,  7]], dtype=int32)>

In [ ]:
tf.random.set_seed(42)
tf.random.shuffle(not_shuffled,seed=42)


<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[10,  7],
       [ 3,  4],
       [ 2,  5]], dtype=int32)>

In [ ]:
not_shuffled =tf.constant([[10,7],[3,4],[2,5]])
tf.random.shuffle(not_shuffled)

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[ 3,  4],
       [ 2,  5],
       [10,  7]], dtype=int32)>

In [ ]:
not_shuffled = tf.constant([[10,7],[3,4],[2,5]])
tf.random.shuffle(not_shuffled)
shuffled = tf.random.shuffle(not_shuffled)
shuffled

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[ 2,  5],
       [ 3,  4],
       [10,  7]], dtype=int32)>

In [ ]:
not_shuffled = tf.constant([[[10,7],[3,4]],[[2,5],[10,7]],[[3,4],[2,5]]])
tf.random.shuffle(not_shuffled)
shuffled = tf.random.shuffle(not_shuffled)
shuffled

<tf.Tensor: shape=(3, 2, 2), dtype=int32, numpy=
array([[[10,  7],
        [ 3,  4]],

       [[ 3,  4],
        [ 2,  5]],

       [[ 2,  5],
        [10,  7]]], dtype=int32)>

In [ ]:
not_shuffled = tf.constant([[[10,7],[3,4],[3,4]],[[2,5],[10,7],[3,4]],[[3,4],[2,5],[3,4]]])
tf.random.shuffle(not_shuffled)
shuffled = tf.random.shuffle(not_shuffled)
shuffled

<tf.Tensor: shape=(3, 3, 2), dtype=int32, numpy=
array([[[ 2,  5],
        [10,  7],
        [ 3,  4]],

       [[ 3,  4],
        [ 2,  5],
        [ 3,  4]],

       [[10,  7],
        [ 3,  4],
        [ 3,  4]]], dtype=int32)>

In [ ]:
not_shuffled = tf.constant([[[10,7],[3,4],[3,4]],[[3,4],[2,5],[3,4]]])
tf.random.shuffle(not_shuffled)
shuffled = tf.random.shuffle(not_shuffled)
shuffled

<tf.Tensor: shape=(2, 3, 2), dtype=int32, numpy=
array([[[ 3,  4],
        [ 2,  5],
        [ 3,  4]],

       [[10,  7],
        [ 3,  4],
        [ 3,  4]]], dtype=int32)>

In [ ]:
tensor1 = tf.constant([1,2,3])
tensor1

<tf.Tensor: shape=(3,), dtype=int32, numpy=array([1, 2, 3], dtype=int32)>

In [ ]:
tensor2 = tf.constant([1,2,3])
tensor2

<tf.Tensor: shape=(3,), dtype=int32, numpy=array([1, 2, 3], dtype=int32)>

In [ ]:
tensor1 + tensor2

<tf.Tensor: shape=(3,), dtype=int32, numpy=array([2, 4, 6], dtype=int32)>

In [ ]:
tensor1 - tensor2

<tf.Tensor: shape=(3,), dtype=int32, numpy=array([0, 0, 0], dtype=int32)>

In [ ]:
tensor1 * tensor2

<tf.Tensor: shape=(3,), dtype=int32, numpy=array([1, 4, 9], dtype=int32)>

In [ ]:
tensor1 / tensor2

<tf.Tensor: shape=(3,), dtype=float64, numpy=array([1., 1., 1.])>

In [ ]:
tf.add(tensor1,tensor2)

<tf.Tensor: shape=(3,), dtype=int32, numpy=array([2, 4, 6], dtype=int32)>

In [ ]:
tf.subtract(tensor1,tensor2)

<tf.Tensor: shape=(3,), dtype=int32, numpy=array([0, 0, 0], dtype=int32)>

In [ ]:
tf.multiply(tensor1,tensor2)

<tf.Tensor: shape=(3,), dtype=int32, numpy=array([1, 4, 9], dtype=int32)>

In [ ]:
tf.divide(tensor1,tensor2)

<tf.Tensor: shape=(3,), dtype=float64, numpy=array([1., 1., 1.])>

In [ ]:
tensor1 = tf.constant(tensor1, dtype=tf.int32)
tensor2 = tf.constant(tensor2, dtype=tf.int32)
tf.add(tensor1,tensor2)

<tf.Tensor: shape=(3,), dtype=int32, numpy=array([2, 4, 6], dtype=int32)>

In [ ]:
#CA1
a = tf.constant([5,7])
b = tf.constant([3,2])
add = tf.add(a,b)
print(add)

tf.Tensor([8 9], shape=(2,), dtype=int32)


In [ ]:
#CA 1 no 60 code

In [ ]:
x = tf.constant(5.0)
y = tf.constant(6.0)
result = tf.subtract(x,y)
print("result of sub :",result.numpy())

result of sub : -1.0


In [ ]:
x = tf.constant(5.0)
y = tf.constant(6.0)
result = tf.add(x,y)
print("result of add :",result.numpy())

result of add : 11.0


In [ ]:
tensor = tf.zeros(shape=(3,2))
tensor

<tf.Tensor: shape=(3, 2), dtype=float32, numpy=
array([[0., 0.],
       [0., 0.],
       [0., 0.]], dtype=float32)>

In [ ]:
#total dabee is 6 divide 6/2 id 2,3
tensor = tf.zeros(shape=(2,3,4,5))
tensor

<tf.Tensor: shape=(2, 3, 4, 5), dtype=float32, numpy=
array([[[[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]]],


       [[[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]]]], dtype=float32)>

In [ ]:
tensor.ndim

4

In [ ]:
#create numpy arrar into tensor
import numpy as np

In [ ]:
numpy_O = np.arange(1,25,dtype=np.int32)
numpy_O

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24], dtype=int32)

In [ ]:
A = tf.constant(numpy_O,shape=(2,3,4))
B = tf.constant(numpy_O)
A,B

(<tf.Tensor: shape=(2, 3, 4), dtype=int32, numpy=
 array([[[ 1,  2,  3,  4],
         [ 5,  6,  7,  8],
         [ 9, 10, 11, 12]],
 
        [[13, 14, 15, 16],
         [17, 18, 19, 20],
         [21, 22, 23, 24]]], dtype=int32)>,
 <tf.Tensor: shape=(24,), dtype=int32, numpy=
 array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
        18, 19, 20, 21, 22, 23, 24], dtype=int32)>)

In [ ]:
A.ndim

3

In [ ]:
B.ndim


1

In [ ]:
#same above create 5 times with different#####

In [ ]:
lol = tf.zeros([2,3,4,5])
lol

<tf.Tensor: shape=(2, 3, 4, 5), dtype=float32, numpy=
array([[[[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]]],


       [[[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]]]], dtype=float32)>

In [ ]:
lol.ndim

4

In [ ]:
lol.shape

TensorShape([2, 3, 4, 5])

In [ ]:
lol.dtype

tf.float32

In [ ]:
tf.rank(lol) # rank means 2*3*4*5 all of lol zeros

<tf.Tensor: shape=(), dtype=int32, numpy=4>

In [ ]:
tf.size(lol)

<tf.Tensor: shape=(), dtype=int32, numpy=120>

In [ ]:
print( lol.ndim)
print( lol.shape)
print( lol.dtype)
print( tf.rank(lol))
print( tf.size(lol))


4
(2, 3, 4, 5)
<dtype: 'float32'>
tf.Tensor(4, shape=(), dtype=int32)
tf.Tensor(120, shape=(), dtype=int32)


In [ ]:
lol[:2,:2,:2,:2]

<tf.Tensor: shape=(2, 2, 2, 2), dtype=float32, numpy=
array([[[[0., 0.],
         [0., 0.]],

        [[0., 0.],
         [0., 0.]]],


       [[[0., 0.],
         [0., 0.]],

        [[0., 0.],
         [0., 0.]]]], dtype=float32)>

In [ ]:
lol[:1,:1,:1,:1]

<tf.Tensor: shape=(1, 1, 1, 1), dtype=float32, numpy=array([[[[0.]]]], dtype=float32)>