In [1]:
import tensorflow as tf

In [3]:
#Random number in tf

In [6]:
random_1 = tf.random.Generator.from_seed(42)
random_1 = random_1.normal(shape=(2,3))
random_1

<tf.Tensor: shape=(2, 3), dtype=float32, numpy=
array([[-0.7565803 , -0.06854702,  0.07595026],
       [-1.2573844 , -0.23193763, -1.8107855 ]], dtype=float32)>

In [8]:
random_num_1 = tf.random.Generator.from_seed(42)
random_num_1 = random_num_1.normal(shape=(2,3))
random_num_1

<tf.Tensor: shape=(2, 3), dtype=float32, numpy=
array([[-0.7565803 , -0.06854702,  0.07595026],
       [-1.2573844 , -0.23193763, -1.8107855 ]], dtype=float32)>

In [9]:
random_num_1,random_1
random_num_1==random_1

<tf.Tensor: shape=(2, 3), dtype=bool, numpy=
array([[ True,  True,  True],
       [ True,  True,  True]])>

In [10]:
not_shuffled = tf.constant([[10,7],[3,4],[2,5]])
tf.random.shuffle(not_shuffled)

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[10,  7],
       [ 3,  4],
       [ 2,  5]], dtype=int32)>

In [16]:
shuffled = tf.random.shuffle(not_shuffled)
shuffled

<tf.Tensor: shape=(2, 3, 2), dtype=int32, numpy=
array([[[10,  7],
        [ 3,  4],
        [ 2,  5]],

       [[10,  7],
        [ 3,  4],
        [ 2,  5]]], dtype=int32)>

In [17]:
not_shuffled = tf.constant([[[10,7],[3,4],[2,5]],[[10,7],[3,4],[2,5]]])
tf.random.shuffle(not_shuffled)
shuffled = tf.random.shuffle(not_shuffled)
shuffled

<tf.Tensor: shape=(2, 3, 2), dtype=int32, numpy=
array([[[10,  7],
        [ 3,  4],
        [ 2,  5]],

       [[10,  7],
        [ 3,  4],
        [ 2,  5]]], dtype=int32)>

In [18]:
tensor1 = tf.constant([1,2,3])
tensor1

<tf.Tensor: shape=(3,), dtype=int32, numpy=array([1, 2, 3], dtype=int32)>

In [20]:
tensor2 = tf.constant([1,2,3])
tensor2

<tf.Tensor: shape=(3,), dtype=int32, numpy=array([1, 2, 3], dtype=int32)>

In [21]:
tensor1+tensor2

<tf.Tensor: shape=(3,), dtype=int32, numpy=array([2, 4, 6], dtype=int32)>

In [22]:
tensor1-tensor2

<tf.Tensor: shape=(3,), dtype=int32, numpy=array([0, 0, 0], dtype=int32)>

In [23]:
tensor1/tensor2

<tf.Tensor: shape=(3,), dtype=float64, numpy=array([1., 1., 1.])>

In [24]:
tensor1*tensor2

<tf.Tensor: shape=(3,), dtype=int32, numpy=array([1, 4, 9], dtype=int32)>

In [25]:
tf.add(tensor1,tensor2)

<tf.Tensor: shape=(3,), dtype=int32, numpy=array([2, 4, 6], dtype=int32)>

In [26]:
tf.subtract(tensor1,tensor2)

<tf.Tensor: shape=(3,), dtype=int32, numpy=array([0, 0, 0], dtype=int32)>

In [27]:
tf.multiply(tensor1,tensor2)

<tf.Tensor: shape=(3,), dtype=int32, numpy=array([1, 4, 9], dtype=int32)>

In [28]:
tf.divide(tensor1,tensor2)

<tf.Tensor: shape=(3,), dtype=float64, numpy=array([1., 1., 1.])>

In [37]:
a = tf.constant([5,7])
b = tf.constant([3,2])
add= tf.add(a,b)
print(add)

tf.Tensor([8 9], shape=(2,), dtype=int32)


In [38]:
a = tf.constant([5,7])
b = tf.constant([3,2])
result= tf.subtract(a,b)
print(result)

tf.Tensor([2 5], shape=(2,), dtype=int32)


In [39]:
tensor = tf.zeros(shape=(3,2))
tensor

<tf.Tensor: shape=(3, 2), dtype=float32, numpy=
array([[0., 0.],
       [0., 0.],
       [0., 0.]], dtype=float32)>

In [40]:
tensor = tf.ones(shape=(3,2))
tensor

<tf.Tensor: shape=(3, 2), dtype=float32, numpy=
array([[1., 1.],
       [1., 1.],
       [1., 1.]], dtype=float32)>

In [42]:
tensor = tf.zeros(shape=(2,3,4,5))
tensor

<tf.Tensor: shape=(2, 3, 4, 5), dtype=float32, numpy=
array([[[[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]]],


       [[[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]]]], dtype=float32)>

In [43]:
tensor.ndim

4

In [44]:
import numpy as np 

In [48]:
numpy_O = np.arange(1,25,dtype=np.int16)
numpy_O

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24], dtype=int16)

In [50]:
A = tf.constant(numpy_O,shape=(2,3,4))
B = tf.constant(numpy_o)
A,B

(<tf.Tensor: shape=(2, 3, 4), dtype=int16, numpy=
 array([[[ 1,  2,  3,  4],
         [ 5,  6,  7,  8],
         [ 9, 10, 11, 12]],
 
        [[13, 14, 15, 16],
         [17, 18, 19, 20],
         [21, 22, 23, 24]]], dtype=int16)>,
 <tf.Tensor: shape=(24,), dtype=int16, numpy=
 array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
        18, 19, 20, 21, 22, 23, 24], dtype=int16)>)

In [51]:
A.ndim

3

In [52]:
B.ndim

1