In [3]:
import tensorflow as tf

In [4]:
t1 = tf.constant([-8, -3])
t2 = tf.constant([10, 7])

In [5]:
tf.abs(t1 + 1)

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([7, 2], dtype=int32)>

In [6]:
t1

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([-8, -3], dtype=int32)>

In [7]:
tf.add(t1, t2)

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([2, 4], dtype=int32)>

In [8]:
import numpy as np
t3 = tf.constant(np.random.randint(0, 280, size=30), dtype=tf.float32)

In [9]:
import numpy as np
t3 = tf.constant(np.random.randint(0, 200, size=30), dtype=tf.float32)

In [10]:
t3.numpy()

array([121., 131.,  92.,  57., 132., 131., 161.,  95.,  33., 187., 103.,
        56., 159.,  13.,   7.,  63., 145., 176., 147.,  44., 122., 109.,
        16.,  81.,  40.,   2.,  54., 198.,  23., 196.], dtype=float32)

In [11]:
tf.size(t3), t3.shape, t3.ndim

(<tf.Tensor: shape=(), dtype=int32, numpy=30>, TensorShape([30]), 1)

In [12]:
tf.reduce_min(t3)

<tf.Tensor: shape=(), dtype=float32, numpy=2.0>

In [13]:
import numpy as np
np.min(t3.numpy())

2.0

In [14]:
tf.reduce_max(t3)

<tf.Tensor: shape=(), dtype=float32, numpy=198.0>

In [15]:
tf.reduce_max(t3)

<tf.Tensor: shape=(), dtype=float32, numpy=198.0>

In [16]:
import numpy as np
np.max(t3.numpy())

198.0

In [17]:
tf.reduce_mean(t3)

<tf.Tensor: shape=(), dtype=float32, numpy=96.46667>

In [18]:
import numpy as np
np.mean(t3.numpy())

96.46667

In [19]:
tf.reduce_sum(t3)

<tf.Tensor: shape=(), dtype=float32, numpy=2894.0>

In [20]:
import numpy as np
np.sum(t3.numpy())

2894.0

In [21]:
# tf.math. reduce_std(t3) #standard deviation using tf
tf.math.reduce_std(t3)

<tf.Tensor: shape=(), dtype=float32, numpy=59.14374>

In [22]:
#  np. std (t3)
# #using numpy
import numpy as np
np.std(t3.numpy())

59.143738

In [23]:
#  tf. math. reduce_variance(t3)
# #variance using tf
tf.math.reduce_variance(t3)

<tf.Tensor: shape=(), dtype=float32, numpy=3497.9822>

In [24]:
# np. var (t3)
# #using numpy
import numpy as np
np.var(t3.numpy())

3497.982

In [25]:
tf.argmax(t3)

<tf.Tensor: shape=(), dtype=int64, numpy=27>

In [26]:
#tf. argmin (t3)
tf.argmin(t3)

<tf.Tensor: shape=(), dtype=int64, numpy=25>

In [27]:
#type casting
# tf. math. reduce_variance(tf.cast (t3,dtype=tf.float32))
tf.cast(t3, dtype=tf.int32)


<tf.Tensor: shape=(30,), dtype=int32, numpy=
array([121, 131,  92,  57, 132, 131, 161,  95,  33, 187, 103,  56, 159,
        13,   7,  63, 145, 176, 147,  44, 122, 109,  16,  81,  40,   2,
        54, 198,  23, 196], dtype=int32)>

In [28]:
tf.random.set_seed(42)
t4 = tf.random.uniform(shape=[30])
t4

<tf.Tensor: shape=(30,), dtype=float32, numpy=
array([0.6645621 , 0.44100678, 0.3528825 , 0.46448255, 0.03366041,
       0.68467236, 0.74011743, 0.8724445 , 0.22632635, 0.22319686,
       0.3103881 , 0.7223358 , 0.13318717, 0.5480639 , 0.5746088 ,
       0.8996835 , 0.00946367, 0.5212307 , 0.6345445 , 0.1993283 ,
       0.72942245, 0.54583454, 0.10756552, 0.6767061 , 0.6602763 ,
       0.33695042, 0.60141766, 0.21062577, 0.8527372 , 0.44062173],
      dtype=float32)>

In [29]:
tf.argmax(t4)

<tf.Tensor: shape=(), dtype=int64, numpy=15>

In [30]:
t4[tf.argmax(t4)]

<tf.Tensor: shape=(), dtype=float32, numpy=0.8996835>

In [31]:

tf.squeeze(t4)

<tf.Tensor: shape=(30,), dtype=float32, numpy=
array([0.6645621 , 0.44100678, 0.3528825 , 0.46448255, 0.03366041,
       0.68467236, 0.74011743, 0.8724445 , 0.22632635, 0.22319686,
       0.3103881 , 0.7223358 , 0.13318717, 0.5480639 , 0.5746088 ,
       0.8996835 , 0.00946367, 0.5212307 , 0.6345445 , 0.1993283 ,
       0.72942245, 0.54583454, 0.10756552, 0.6767061 , 0.6602763 ,
       0.33695042, 0.60141766, 0.21062577, 0.8527372 , 0.44062173],
      dtype=float32)>

In [33]:
# tf. random. set_seed (42)
tf.squeeze(t4)


<tf.Tensor: shape=(30,), dtype=float32, numpy=
array([0.6645621 , 0.44100678, 0.3528825 , 0.46448255, 0.03366041,
       0.68467236, 0.74011743, 0.8724445 , 0.22632635, 0.22319686,
       0.3103881 , 0.7223358 , 0.13318717, 0.5480639 , 0.5746088 ,
       0.8996835 , 0.00946367, 0.5212307 , 0.6345445 , 0.1993283 ,
       0.72942245, 0.54583454, 0.10756552, 0.6767061 , 0.6602763 ,
       0.33695042, 0.60141766, 0.21062577, 0.8527372 , 0.44062173],
      dtype=float32)>

In [34]:
# tf. random. set_seed (42)
tf.random.set_seed(42)
t5 = tf.constant(tf.random.uniform(shape=[30]), shape=(1, 1, 1, 30))
t5.numpy()

array([[[[0.6645621 , 0.44100678, 0.3528825 , 0.46448255, 0.03366041,
          0.68467236, 0.74011743, 0.8724445 , 0.22632635, 0.22319686,
          0.3103881 , 0.7223358 , 0.13318717, 0.5480639 , 0.5746088 ,
          0.8996835 , 0.00946367, 0.5212307 , 0.6345445 , 0.1993283 ,
          0.72942245, 0.54583454, 0.10756552, 0.6767061 , 0.6602763 ,
          0.33695042, 0.60141766, 0.21062577, 0.8527372 , 0.44062173]]]],
      dtype=float32)

In [35]:
t6 = tf.squeeze(t5)
t6

<tf.Tensor: shape=(30,), dtype=float32, numpy=
array([0.6645621 , 0.44100678, 0.3528825 , 0.46448255, 0.03366041,
       0.68467236, 0.74011743, 0.8724445 , 0.22632635, 0.22319686,
       0.3103881 , 0.7223358 , 0.13318717, 0.5480639 , 0.5746088 ,
       0.8996835 , 0.00946367, 0.5212307 , 0.6345445 , 0.1993283 ,
       0.72942245, 0.54583454, 0.10756552, 0.6767061 , 0.6602763 ,
       0.33695042, 0.60141766, 0.21062577, 0.8527372 , 0.44062173],
      dtype=float32)>