In [1]:
pip install --upgrade pip 

Note: you may need to restart the kernel to use updated packages.


In [2]:
pip install tensorflow

Note: you may need to restart the kernel to use updated packages.


In [4]:
import tensorflow as tf
print(tf.__version__)

2.16.1


In [5]:
scaler = tf.constant(5,6)
scaler

<tf.Tensor: shape=(), dtype=int8, numpy=5>

In [6]:
scaler.ndim

0

In [10]:
vector = tf.constant([[[5,6],[5,6]]])

In [11]:
vector

<tf.Tensor: shape=(1, 2, 2), dtype=int32, numpy=
array([[[5, 6],
        [5, 6]]], dtype=int32)>

In [12]:
vector.ndim

3

In [14]:
vector = tf.constant([[5,6],[5,6],[5,6]])
vector

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[5, 6],
       [5, 6],
       [5, 6]], dtype=int32)>

In [15]:
vector.ndim

2

In [25]:
matrix = tf.constant([[10,6],[10,6],[10,6]],dtype=tf.int16)
matrix

<tf.Tensor: shape=(3, 2), dtype=int16, numpy=
array([[10,  6],
       [10,  6],
       [10,  6]], dtype=int16)>

In [24]:
matrix.ndim

3

In [33]:
tensor = tf.constant([[[[1,2,3],[1,2,3]],[[1,2,3],[1,2,3]],[[1,2,3],[1,2,3]]]],dtype=tf.int16)

In [34]:
tensor

<tf.Tensor: shape=(1, 3, 2, 3), dtype=int16, numpy=
array([[[[1, 2, 3],
         [1, 2, 3]],

        [[1, 2, 3],
         [1, 2, 3]],

        [[1, 2, 3],
         [1, 2, 3]]]], dtype=int16)>

In [35]:
tensor.ndim

4

In [36]:
tensor = tf.Variable([[10,6],[10,6],[10,6]])
tensor

<tf.Variable 'Variable:0' shape=(3, 2) dtype=int32, numpy=
array([[10,  6],
       [10,  6],
       [10,  6]], dtype=int32)>

In [37]:
tensor = tf.Variable([[[[1,2,3],[1,2,3]],[[1,2,3],[1,2,3]],[[1,2,3],[1,2,3]]]],dtype=tf.int16)

In [38]:
tensor

<tf.Variable 'Variable:0' shape=(1, 3, 2, 3) dtype=int16, numpy=
array([[[[1, 2, 3],
         [1, 2, 3]],

        [[1, 2, 3],
         [1, 2, 3]],

        [[1, 2, 3],
         [1, 2, 3]]]], dtype=int16)>

In [40]:
matrix = tf.Variable([[10,6],[10,6],[10,6]],dtype = tf.int16)
matrix

<tf.Variable 'Variable:0' shape=(3, 2) dtype=int16, numpy=
array([[10,  6],
       [10,  6],
       [10,  6]], dtype=int16)>

In [41]:
matrix.assign([[10,2],[10,4],[10,3]])

<tf.Variable 'UnreadVariable' shape=(3, 2) dtype=int16, numpy=
array([[10,  2],
       [10,  4],
       [10,  3]], dtype=int16)>

In [42]:
matrix

<tf.Variable 'Variable:0' shape=(3, 2) dtype=int16, numpy=
array([[10,  2],
       [10,  4],
       [10,  3]], dtype=int16)>

In [43]:
changeable_tensor = tf.Variable([10,4])
uc_ten = tf.constant([10,4])
changeable_tensor,uc_ten
changeable_tensor==uc_ten

<tf.Tensor: shape=(2,), dtype=bool, numpy=array([ True,  True])>

In [45]:
changeable_tensor[0].assign(29)
changeable_tensor

<tf.Variable 'Variable:0' shape=(2,) dtype=int32, numpy=array([29,  2], dtype=int32)>

In [50]:
raj = tf.random.Generator.from_seed(42)
raj = raj.normal(shape=(1,3))

In [51]:
raj

<tf.Tensor: shape=(1, 3), dtype=float32, numpy=array([[-0.7565803 , -0.06854702,  0.07595026]], dtype=float32)>

In [52]:
raj.ndim

2

In [53]:
raj.shape

TensorShape([1, 3])

In [54]:
not_shuffled = tf.constant([[[10,7],[3,4],[3,4]],[[2,5],[10,7],[3,4]],[[3,4],[2,5],[3,4]]])
tf.random.shuffle(not_shuffled)


<tf.Tensor: shape=(3, 3, 2), dtype=int32, numpy=
array([[[10,  7],
        [ 3,  4],
        [ 3,  4]],

       [[ 2,  5],
        [10,  7],
        [ 3,  4]],

       [[ 3,  4],
        [ 2,  5],
        [ 3,  4]]], dtype=int32)>

In [55]:
shuffled = tf.random.shuffle(not_shuffled)
shuffled

<tf.Tensor: shape=(3, 3, 2), dtype=int32, numpy=
array([[[ 3,  4],
        [ 2,  5],
        [ 3,  4]],

       [[ 2,  5],
        [10,  7],
        [ 3,  4]],

       [[10,  7],
        [ 3,  4],
        [ 3,  4]]], dtype=int32)>

In [56]:
not_shuffled = tf.constant([[[100,17],[33,44],[36,47]],[[82,59],[910,97],[3,4]],[[3,4],[2,5],[3,4]]])
tf.random.shuffle(not_shuffled)


<tf.Tensor: shape=(3, 3, 2), dtype=int32, numpy=
array([[[ 82,  59],
        [910,  97],
        [  3,   4]],

       [[  3,   4],
        [  2,   5],
        [  3,   4]],

       [[100,  17],
        [ 33,  44],
        [ 36,  47]]], dtype=int32)>

In [58]:
shuffled = tf.random.shuffle(not_shuffled)
shuffled

<tf.Tensor: shape=(3, 3, 2), dtype=int32, numpy=
array([[[100,  17],
        [ 33,  44],
        [ 36,  47]],

       [[  3,   4],
        [  2,   5],
        [  3,   4]],

       [[ 82,  59],
        [910,  97],
        [  3,   4]]], dtype=int32)>

In [59]:
shuffled = tf.random.shuffle(not_shuffled)
shuffled

<tf.Tensor: shape=(3, 3, 2), dtype=int32, numpy=
array([[[ 82,  59],
        [910,  97],
        [  3,   4]],

       [[100,  17],
        [ 33,  44],
        [ 36,  47]],

       [[  3,   4],
        [  2,   5],
        [  3,   4]]], dtype=int32)>

In [67]:
rajj = tf.constant([1,2,3])
rajj

<tf.Tensor: shape=(3,), dtype=int32, numpy=array([1, 2, 3], dtype=int32)>

In [68]:
sajj = tf.constant([1,2,3])
sajj

<tf.Tensor: shape=(3,), dtype=int32, numpy=array([1, 2, 3], dtype=int32)>

In [69]:
rajj + sajj

<tf.Tensor: shape=(3,), dtype=int32, numpy=array([2, 4, 6], dtype=int32)>

In [70]:
rajj - sajj

<tf.Tensor: shape=(3,), dtype=int32, numpy=array([0, 0, 0], dtype=int32)>

In [71]:
rajj / sajj

<tf.Tensor: shape=(3,), dtype=float64, numpy=array([1., 1., 1.])>

In [72]:
rajj *sajj

<tf.Tensor: shape=(3,), dtype=int32, numpy=array([1, 4, 9], dtype=int32)>

In [73]:
tf.add(rajj,sajj)

<tf.Tensor: shape=(3,), dtype=int32, numpy=array([2, 4, 6], dtype=int32)>

In [74]:
tf.subtract(rajj,sajj)

<tf.Tensor: shape=(3,), dtype=int32, numpy=array([0, 0, 0], dtype=int32)>

In [75]:
tf.multiply(rajj,sajj)

<tf.Tensor: shape=(3,), dtype=int32, numpy=array([1, 4, 9], dtype=int32)>

In [76]:
tensor = tf.zeros(shape=(2,3,4,5))

In [77]:
tensor

<tf.Tensor: shape=(2, 3, 4, 5), dtype=float32, numpy=
array([[[[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]]],


       [[[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]]]], dtype=float32)>

In [80]:
tensor = tf.zeros(shape=(2,3,3,4))
tensor

<tf.Tensor: shape=(2, 3, 3, 4), dtype=float32, numpy=
array([[[[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]],

        [[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]],

        [[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]]],


       [[[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]],

        [[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]],

        [[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]]]], dtype=float32)>

In [81]:
import numpy as np

In [82]:
numpy_0 = np.arange(1,25,dtype = np.int32)
numpy_0

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24], dtype=int32)

In [83]:
lol = tf.zeros([2,3,4,5])
lol

<tf.Tensor: shape=(2, 3, 4, 5), dtype=float32, numpy=
array([[[[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]]],


       [[[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]]]], dtype=float32)>

In [84]:
lol.ndim

4

In [85]:
lol.shape

TensorShape([2, 3, 4, 5])

In [86]:
lol.dtype

tf.float32

In [87]:
tf.size(lol)

<tf.Tensor: shape=(), dtype=int32, numpy=120>

In [89]:
loll = tf.zeros([2,3,4,5])
loll

<tf.Tensor: shape=(2, 3, 4, 5), dtype=float32, numpy=
array([[[[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]]],


       [[[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]]]], dtype=float32)>

In [90]:
loll[:2,:2,:2,:2]

<tf.Tensor: shape=(2, 2, 2, 2), dtype=float32, numpy=
array([[[[0., 0.],
         [0., 0.]],

        [[0., 0.],
         [0., 0.]]],


       [[[0., 0.],
         [0., 0.]],

        [[0., 0.],
         [0., 0.]]]], dtype=float32)>

In [91]:
loll[:1,:1,:1,:1]

<tf.Tensor: shape=(1, 1, 1, 1), dtype=float32, numpy=array([[[[0.]]]], dtype=float32)>