In [5]:
pip install --upgrade pip

Note: you may need to restart the kernel to use updated packages.


In [6]:
pip install tensorflow

Note: you may need to restart the kernel to use updated packages.


In [7]:
import tensorflow as tf
print(tf.__version__)

2.16.1


In [8]:
scaler = tf.constant(5,6)
scaler

<tf.Tensor: shape=(), dtype=int8, numpy=5>

In [9]:
scaler.ndim

0

In [10]:
vector = tf.constant([[5,6],[5,6]])
vector

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[5, 6],
       [5, 6]], dtype=int32)>

In [11]:
vector = tf.constant([[[5,6],[5,6],[5,6]]],dtype = tf.int16)
vector.ndim
vector

<tf.Tensor: shape=(1, 3, 2), dtype=int16, numpy=
array([[[5, 6],
        [5, 6],
        [5, 6]]], dtype=int16)>

In [ ]:
matrix = tf.constant([[10,6],[10,6],[10,6]],dtype=)